export default [
    {
        id:123,
        imageUrl: "https://klike.net/uploads/posts/2019-05/medium/1556708030_2.jpg",
        name: "this is name",
        description: "description description description description description description description description description description",
        lastComment: "17.06.2023",
    },
    {
         id:1233,
        imageUrl: "https://klike.net/uploads/posts/2019-05/medium/1556708030_2.jpg",
        name: "this is name",
        description:"description description description description description description description description description description",
        lastComment: "17.06.2023",
    },
    {
         id:1231,
        imageUrl: "https://klike.net/uploads/posts/2019-05/medium/1556708030_2.jpg",
        name: "this is name",
        description: "description description description description description description description description description description",
        lastComment: "17.06.2023",
    },
    {
         id:12319,
        imageUrl: "https://klike.net/uploads/posts/2019-05/medium/1556708030_2.jpg",
        name: "this is name",
        description: "description description description description description description description description description description",
        lastComment: "17.06.2023",
    },
    {
         id:122,
        imageUrl: "https://klike.net/uploads/posts/2019-05/medium/1556708030_2.jpg",
        name: "this is name",
        description: "description description description description description description description description description description",
        lastComment: "17.06.2023",
    },
    {
         id:631,
        imageUrl: "https://klike.net/uploads/posts/2019-05/medium/1556708030_2.jpg",
        name: "this is name",
        description: "description description description description description description description description description description",
        lastComment: "17.06.2023",
    },
    {
         id:1331,
        imageUrl: "https://klike.net/uploads/posts/2019-05/medium/1556708030_2.jpg",
        name: "this is name",
        description: "description description description description description description description description description description",
        lastComment: "17.06.2023",
    },
    {
         id:123341,
        imageUrl: "https://klike.net/uploads/posts/2019-05/medium/1556708030_2.jpg",
        name: "this is name",
        description: "description description description description description description description description description description",
        lastComment: "17.06.2023",
    },
    {
         id:1212131,
        imageUrl: "https://klike.net/uploads/posts/2019-05/medium/1556708030_2.jpg",
        name: "this is name",
        description: "description description description description description description description description description description",
        lastComment: "17.06.2023",
    },
    {
         id:12323231,
        imageUrl: "https://klike.net/uploads/posts/2019-05/medium/1556708030_2.jpg",
        name: "this is name",
        description: "description description description description description description description description description description",
        lastComment: "17.06.2023",
    },
    {
         id:123891,
        imageUrl: "https://klike.net/uploads/posts/2019-05/medium/1556708030_2.jpg",
        name: "this is name",
        description: "description description description description description description description description description description",
        lastComment: "17.06.2023",
    },
]